### ISSUE TITLE
Set encoding explicitly

### ISSUE THREAD

**Issue by toothfairy** [slate/slate-irc#19]
Hi there
I wonder if explicit setting of encoding for stream is a must https://github.com/slate/slate-irc/blob/master/index.js#L48. Node's string decoder has "utf8" as a default encoding. And that line makes it impossible to use your library to support old-school and esoteric irc servers with different encodings such as cp1251

**Comment by erming** [comment]
Hey, I've now added the option to change the encoding, but with the fallback to 'utf-8'.

The commit is here: https://github.com/slate/slate-irc/commit/37567d5fa36eb829ce44a9c06487ba42521fc0b7

I'll close this issue. Thanks!

**Comment by TuSuNaMi** [comment]
Hi;

My server encoding iso-8859-9 and i changed this value because utf8 dont work 
  stream.setEncoding(encoding || 'binary');

However binary encoding made problem with Turkish characters this solved or not ?

Thanks

**Comment by ErKaNs** [comment]
@erming are you solved  iso-8859-9 charset?

**Comment by ErKaNs** [comment]
up

**Comment by ErKaNs** [comment]
ğĞıİşŞ have problem this characters �������
