### ISSUE TITLE
I want to maintain 'slate-irc' and 'slate-irc-parser' project.

### ISSUE THREAD

**Issue by simnalamburt** [slate/slate-irc#40]
Hy folks and @tj! My name is Hyeon Kim and I want to be a collaborator of 'slate-irc' and 'slate-irc-parser' project.

I'm currently running [openirc](https://github.com/openirc/openirc) project, and it needs IRC client library written in node.js and I choosed slate-irc for it.

But several days later, I had to fork the slate-irc and slate-irc-parser project in to [openirc/qbirc](https://github.com/openirc/qbirc) [openirc/qbirc-parser](https://github.com/openirc/qbirc-parser) because of the cross IRC scripting vulnerability. It happened while I write [simnalamburt/hyeonbot](https://github.com/simnalamburt/hyeonbot/blob/master/src/main.js#L72).

```js
irc.send('#slate', `Hi ${msg}, I'm robot!`);

// If msg is 'blablabla\r\nMODE #slate -o AnotherUser\r\nPRIVMSG #hyeon :'
// The robot will send a 'Hi blablabla' message and deop the 'AnotherUser'
```

Beside that we had many reasons to fork those 2 projects; ES2015, CI, 1.0, etc. I made a [roadmap](https://github.com/simnalamburt/qbirc/issues/1) for both project, but I just realized that it would be better if I can be a collaborator of both project.

I currently not planning to contribute into the [slate/slate](https://github.com/slate/slate) project, but if you add me as a new member of slate GitHub group, maybe I can give you some help with it.

If you are interested, please let me know!

**Comment by tj** [comment]
added!

**Comment by simnalamburt** [comment]
@tj Thanks!
