### ISSUE TITLE
Enable travis CI

### ISSUE THREAD

**Issue by simnalamburt** [slate/slate-irc#42]
It's same problem with <https://github.com/slate/slate-irc-parser/issues/5>. I want to enable the Travis CI with this project but I couldn't because of lack of the admin access.

![2016-07-02 2 19 06](https://cloud.githubusercontent.com/assets/4435445/16529018/6146d28a-3ffb-11e6-9823-021266c271e8.png)

@tj, can you help me out? Thanks! 😃

**Comment by simnalamburt** [comment]
@erming @krainboltgreene Do you have any admin access?

**Comment by simnalamburt** [comment]
:cry:

**Comment by tj** [comment]
Should have admin on both now sorry!

**Comment by simnalamburt** [comment]
Thanks!
