### ISSUE TITLE
no changelog entry for v0.9.1

### ISSUE THREAD

**Issue by brandly** [slate/slate-irc#46]
interested in seeing what's changed! thanks 

(i've used this in [Lax](https://github.com/brandly/Lax) for quite a while)

**Comment by simnalamburt** [comment]
I just refactored codes in modern JS, and behavior is not changed at all.
(If any behavior has changed, it’s bug)

2020년 8월 30일 (일) 08:59, Matt Brandly <notifications@github.com>님이 작성:

**Comment by simnalamburt** [comment]
Update CHANGELOG.md. Thanks!
